# Generated by Django 6.0.5 on 2026-08-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstate',
            name='step_data',
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='needs_redo_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='step_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='current_step',
            field=models.CharField(default='upload', max_length=50),
        ),
    ]
